apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chat-application
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data
